language: bash
script:
- shellcheck ./unlocked.sh
- mkdir -p deploy
- cp ./unlocked.sh ./deploy/
deploy:
  provider: s3
  bucket: unlocked.agrim.io
  local-dir: deploy
  skip_cleanup: true
  acl: public_read
  region: us-west-1
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
