language: bash
script:
- shellcheck ./unlocked.sh
- mkdir -p deploy
- cp ./unlocked.sh ./deploy/
deploy:
  provider: s3
  bucket: unlocked.agrim.io
  local-dir: deploy
  cleanup: true
  acl: public_read
  region: us-west-1
  secret_access_key:
    secure: "MXX44coTqHs6IbWh8G4Y4FvaVf5UOcUOHGTgEAHE5glBGds8QC8D9tjGMGlLH9IplkT2ZzBCyuHym1/Vpk7RYgd6YiqOAd47SrV+heTz8oR++uVMGo7rgv1vmAwIMlt+uoNwThm8mvvZ9N61GRdpMQFvJTXDs/CjEkO56wZ6gAbqnueuRiLuUMMyNzGJhd9sDznW+ZLewUDjfWnWY8eV16WEblkUbiSXDYi15s0CkOqkodani0QTXgK/Rn7DYh6qOmoFwSYltCfeCw4y9BfwfHMgnHjZA9MkerKCYZaI8GpNgktzsjoyUdDHi+3OIDgQyb89V77PcqgmRUgqTZaP0Ik2lPXN0w44xsw0/hjAf8hGuhLfLPuGDVitwIB2lGecs/TWHqyDYt3m7qrWaH94EHclut23pnJUTEZ+ssRu0I9cedTxyeMw8w/HDW0CuKdyM0YDb5rxHlbac7AykfidOq44PaJv4tVyNOEZzScWK9HFLZPzvTW3wTbhUvXa6FM3P27H+s2hVEiFAXUPbRZbKtDz5KQpgqKuN43iN1XPgfcRfTfxSu/n0rLxjV1jLiVte0O6iVk7zlWo8iy54fmQ8jFKM1tGv/cRAtyBvYpQ2Y+oqVoa0BiWqGnaTsZLy5RNUnmi29w2jTo3Z/1GZgYxWKrsOSlDIw6V6faWCJcRBSY="
  access_key_id:
      secure: "xywj09MyDd3Ama54E4y19vn9fhE49MhaHwvqDPRO6B5sX783HAoERHvyy3s/iR7DAUI3goLDn3zk7t8NdQ9fAClBP6zggJGbbgo0PYtGdra12+X2M4okhyONTu1jw1yPvoHBWmKLThbBVD7kqXZquWUN/+dtW/+s/U8Kat3NeuhmbwUcDY1YVVrSLn42E6RR0cKgqif7hM6ex1PPMP7CIPV1u01AB11mVNK6udPL+qai6vvj27nAm8nfyCjrrtnuPiXy4AJHTfgXlYu493EcGaHNIgFLj8OQmwBWY/Xlyz0kb135UnfZPn1uGQdicsYguh12ZM7A9KlM83VvKKaOhuTG8QD5DFntJTpXY10kQpqXmNuIA3MKwylVLZc8+hP/giOCEOQHZNG5MJ5tJZ6xcMTkivChV6Qv52kafrvOUQLSOK2hiKG6et1UQL7NcwZwELK0z5tb0nugEv0WVK0L5Z8CpYJ4zXySqIkH0eeTn1FuYUbEtKMqZu5YESKEg8yEP9YMwfV7Sxn1qsR/kHTbADkUIkYx5590QoA+g6uR8IZ/1YLDmOJQ6zOlS3h+5aDhCTkENhM159s8jzzufiH5tZa6P+4Q/rPwv7ObuaqPXZbsR6OOFI2BxFa6WV5AlpKFvGs9ZypZ5SMDn01QFtNKKhVGYxyEbhT2Xe8bxbelTsw="
