language: bash
script:
- shellcheck ./unlocked.sh
- mkdir -p deploy
- cp ./unlocked.sh ./deploy/
deploy:
  provider: s3
  bucket: unlocked.agrim.io
  local-dir: deploy
  skip_cleanup: true
  acl: public_read
  region: us-west-1
  secret_access_key:
    secure: "RdsUfiWfPVTAcfN35NNqOD1BrY0xXsJzNbR/ztc+MjAYSYOLt+9COy64vmAWLNnAU9ytZseyiWtgnNm0ChM3UBfRbkVPwedVKAeD3B0AKoHzn6lCsgeqYw7RYKWQJ9FQ//tBT0zUgcwo6Bx6+gN3gMVmOaSmvlNjxTLp3SQvyFyiq4c9hV1VNfx+879qKFjVzO9j+DbavbMHsN4LsWbGLd7xKDGKK8wQeJlMAv79Khz8jDntxHZQViIiwtOU5xQGs9qRRFhpJisc5xEa8OKes+IEA+VH9Ngg5VjBshe9mVXLBeccCzxmVEgqy0qveVVhKZeOTtpeS4SnPtkm0rwO8T8Xyt7znMeZv9c7R1d8XAOBGLfw0P5sfButNkLULUwg+rR43ZfyWlrV1SyObNKHTPxjSP+grWuR0s8iar4b6zbnOOs/QCmhiRkASYGKWhxqgUjUaTdtrlxjbSvTB2vkAQzJ34xbLUaOhaQR92xT8oN0CFALj0EBClj0b1iqwRd7xtm3SRBSe4NZdsqgIFLB17Y0elrkwFiTEPN97T0n3N/XA4Af5XJBbU0xCb0dNTss8SUjEKhI3lpRMrhdGL0X4YS0Tq4Rvt91buB1lUas6ShLq7p/WCEayFwyyJiqKn0q4K3yNfqu4zCGeypjFgf47otcetblDYHci2M/bSUzFRA="
  access_key_id:
    secure: "yuwQCPbI8Kvu8BwTWruL6uNP8Dxaooj519Q41b6FLua5GF15NqK9G+JQloX2gNigDQ6UyvTeFQ4zYV3k4Xz+CZ3el20HttuIbLb5qr+baOi2rxE6ZeLDU6vyHpG9ahyPjBkfXUkBrwX1bIW2r7OHZxKGGJpDMOm7xTIpymDDl0NZAoFj8HV761hkvAmObwKxfkZ5ri2cU6FeOS3uW2vmJEykkrF36QEINcZ8CKI7p/arnD0GR1/QQC9Emr1X7K3tEMtmKrPMZVr74WTsBX+yk+cTN3exxqbSnnCR6ByW48G3AfOBabztJqkc+y6Y8y9G5fkfvnRJTlXQlxbiix057lEesBGw9X9UQ46aGvvA/jau/DVGfIX9Dypt7jyoJ7QNB72mNFmpDM5ZtWmGU3a5TuPW2UWELft66SqHOrqMA8K7H91fJyZkF8mFO4XeZUFRsPR70xElEkwO+Q50K9x1iRbKpnQQ8xtk2qXANm1ZkvvbXPU1TGBkl0e7w5sifMEe+V0UsYpEJH1dFDFug46BScXf+2NVNTLfKz098s6weu81lFPzD53LMZ8KvZ/FZXTEW0V4rfj00acfaZyFPHB4TMjjuHN34TCf8QaG48jwlzfYKrckOWLEUKanZvEk/KRsK6KYJrlo26Tmf8PraIjp0E5t3jcAY3DxwNYOYzn9Yg0="
