language: bash
script:
- shellcheck ./unlocked.sh
- mkdir -p deploy
- cp ./unlocked.sh ./deploy/
deploy:
  provider: s3
  bucket: unlocked.agrim.io
  local-dir: deploy
  skip_cleanup: true
  acl: public_read
  region: us-west-1
  secret_access_key:
    secure: mPY+nyvujit8TmPKjIk/1g6hfB+afaxOyObzvm+e6BMgwhlg8vYS9PF39Bj0QsuUhDWPizmT4YYw0q9jbpuFJ8ugVeknvec+cuHFk3WKvU2/c9/HxmZ6CTYR6Gk8suBWktUe5noqzNmvEzR0LsmA6Kvs7LLDI1VAo7XmoSvFNgk0YgqFlDcJc3QgdZp1isD+AN8KeVl5ZBmMfmBXBFGMbIZYoV3ab0rMzFdTgdL5dWByoWX7Sejnhl/rdUtHFHlMkDA4zRnlCFG8RA0ChIu4uf13hthIgOPsGIqbC6I+CXRvH113N/egzqluCNP0MZrHrY2PiBChr2X1RZWvmP7TYNCV5gV+OAN60RuDle9Gm7/9KAScbK8+nhTFLU94Vh8DXjFJ49eHjpu7Xun66LlFYSjFAVbcvcgmaPk1A/ncrzENBhs+CbSzjaLjGaDV6qj7zlzV+yhiBteS5XLHBz7dRmE/yleLhfZCkujh985tLMcBN+ZtCY4+BPkYq3R1drZ9I5qM3wPBjEUhHLxmKYFAVQU86jfejL7lqbtMv6u2uHsnSBH+EFSAWN4zi/MfPtzX1qWaozRau10Oc70w3WLV8N7vH4vpm6JRebHgkSsDJ/6j55BY5MQDPWgmSKJZXXtlijaK6Iq3ENcFPn3oj4c5BTwOUc1wUbrBfAW/p2XVR0o=
  access_key_id:
    secure: AyMA3vpO2b2wBD5oPmtGoSu9ll0SC0+aOPNFegjysKorN3CU1w3JvEz6K4zUiROgZVJfFN4UM8zjRduJLeyz4TY/BdPCF6C0rkbbYVqhGbcMnlevXsvcuwHuGOo8+k9W3GUZ1rAvGFmFFsBWQ13v4jC69fomtRyeGbkZnZ3GQplEOA1Ii08HBl/tz4woIEIFjK76CGWiOwqUidqAFzVHgNgtyXtIBtoPeZNvuDZytPSA8KltAsyEEFfRefryCWrtlelql4mx+whpzkBJlxB4zhEbu1vlUmNKGnnqcT6h9FS7CIHUrfuX1QvZh5pl6GwUMYJZ1UEnYNtFWipwR5d5Oko8B4kb8jVqT3xOXGTitgX5R3ac5xZbqk73h4GS5ZUkrRoQnAY+Kp9W4Rb+5d8M630QCgKnM3+FUoR0Kg+SxRUsXbJtlIVsk1Wz7Mt+PZYPk9rdzdFQDsLN5W3MSesjBF7A+QoeVHUCho36Om0+27xh8qOz6eflv+J1pfrMh8iHDNlWk6UMaIpoFyZitXDMy7Kvo0sqJrkQREm/ja29QGZv1tRwRp3GOIajhaVDjO+g2zDv9JYnWcCNGDB3WEPAISUZUcqxaYW/cV8gGiHv/rbsU7bHTL01FdANO+DjlPwoo6SBDyeLfG6nzMpeifdAb8fAq5GGRGdzoNiYHpbw5BU=
